
labels: ["error", "Non-English"]
body:
  - type: markdown
    attributes:
      value: |
        # 投稿ルール
        
        本掲示板（Discussions）はユーザー同士の助け合いの場です。何に困っているのかを分かりやすく、詳しくお書きいただくほど、返信コメントを得られる可能性が高くなります。
        
        - コメントで助言・提案をもらったら、なるべく早急に試してみて、問題が解決したかどうかを投稿してください
        - 解決した場合は、助言・提案どおりの操作で解決したのか、何かほかの操作を加える必要があったのかを書き添えてください。
        - 解決した場合は、「Mark as answer」をクリックすることで、解決につながったコメントを「answer」としてマークしてください。
        
        # 各種資料
        
        投稿をしなくても、次の資料にあたることで解決する場合があります。
        
        - [「よくある質問」ページ](https://khcoder.net/FAQ.html)
        - [既存のDiscussions](https://github.com/ko-ichi-h/khcoder/discussions?discussions_q=) （検索可）
        - [旧掲示板](http://koichi.nihon.to/cgi-bin/bbs_khn/khcf.cgi) （検索可）
        - [公式入門書](https://amzn.to/3iyPimF)
        - [詳細マニュアル +alpha](http://amzn.to/2wHFxKg)
        
        # 記入欄
        
  - type: input
    id: version
    attributes:
      label: "お使いのKH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。「3」だけでなく必ず「3.00 official-package」「3.Beta.08e」のように正確に記入してください。"
      placeholder: "記入例：3.Beta.08e, 3.00 official-package など。"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "バグについて詳しくお書きください"
      description: "すでに入力されているテンプレートを編集しながらご記入ください"
      value: |
        ■お使いのOS
        →記入例：Windows 11, Windows 10, macOS 14, Ubuntu 18.04など
        
        ■KH Coderのインストール先フォルダ（解凍先フォルダ）
        →KH Coder起動時のコンソール画面の最上部に「CWD: C:\\KHCoderOfficialPackage」のように表示されます。
        →ご自身で変更していなければC:\\KHCoderOfficialPackageとなっていることが多いでしょう。
        →記入例：C:\\KHCoderOfficialPackage
        
        ■どんなバグですか？
        →「うまくいかない」のようなあいまいな書き方ではなく、「○○の結果を期待していたが、□□の結果になった」のように、できるだけ具体的にお書きください。
        →記入例：共起ネットワーク作成時に○△□を使おうとするとエラーになる。
        
        ■スクリーンショット
        状況をあらわすようなスクリーンショットを添付していただくと、解決する可能性が高まります。
        
        ■どのように操作すればそのバグを再現できますか？
        →記入例：
        1. メニューから「ツール」「抽出語」「共起ネットワーク」を順にクリック
        2. 開いた「抽出語・共起ネットワーク：オプション」画面で「○△□」にチェックを入れてから「OK」をクリック
        
        ■エラー・メッセージ
        →エラーが出ている場合は、省略や意訳をしていない一字一句そのままのエラーメッセージをお書きください。あるいはエラー画面・問題が起こった画面のスクリーンショットを添付してください。
        
        ■その問題はチュートリアルの漱石「こころ」データでも同様に発生しましたか？
        →データに原因があるのか、ほかに原因があるのかを区別するために、チュートリアル・データでも同じ操作をお試しください。
        →記入例：はい、いいえ、他
        
        ■その問題を再現できるファイル（群）
        →その問題を再現できる分析対象ファイル等をなるべく添付してください。必要に応じてZip圧縮して添付してください。チュートリアルとして同梱されているファイルのみで問題を再現可能な場合は不要です。
        
        ■分析しようとしているのは何語のテキストですか？
        →記入例：日本語、英語、ロシア語、中国語など
        
        ■分析対象として指定しているファイルの形式は何ですか？
        →記入例：テキスト形式（.txt）、Excel形式（.xlsx）、CSV形式（.csv）など
        
        ■お使いのセキュリティ対策／ウイルス対策ソフトウェア
        →記入例：Norton 360, ウイルスバスター Corp Clientなど
        
        ■お使いのCPU
        →不明の場合はPCの機種名をお書きいただいてもOKです。
        →記入例：Intel Core i5, AMD Ryzen 5, Apple M1, Microsoft SQ2など
    validations:
      required: true

  - type: markdown
    id: console
    attributes:
      value: |
        hogehoge
        hoge
    validations:
      required: true
