
title: "できるだけ具体的に状況をあらわすタイトルをここに入力してください"
labels: ["error", "Non-English"]
body:
  - type: markdown
    attributes:
      value: |
        # 投稿の前に
        
        本掲示板（Discussions）はユーザー同士の助け合いの場です。何に困っているのかを分かりやすく、詳しくお書きいただくほど、応答を得られる可能性が高くなります。
        
        もし確実に応答を得たい場合は、㈱SCREEN アドバンストシステムソリューションズ様ご提供の[「KH Coderサポートパッケージ」](https://www.screen.co.jp/as/solution/khcoder)（Pro Edition以上）を購入することで、 同社のQ & A対応窓口を利用できます。
        
        投稿した問題が解決したら、解決につながったコメントを「answer」としてマークし、どのように解決したのかを報告しましょう。
        
        # 各種資料
        
        投稿をしなくても、次の資料にあたることで解決する場合があります。
        
        - [「よくある質問」ページ](https://khcoder.net/FAQ.html)
        - [既存のDiscussions](https://github.com/ko-ichi-h/khcoder/discussions?discussions_q=) 検索可！
        - [旧掲示板](http://koichi.nihon.to/cgi-bin/bbs_khn/khcf.cgi) 検索可！
        - [公式入門書](https://amzn.to/3iyPimF)
        - [詳細マニュアル +alpha](http://amzn.to/2wHFxKg)
        
        # 記入欄
        
  - type: input
    id: version
    attributes:
      label: "KH Coderのバージョン"
      description: "KH Coderのメニューから「ヘルプ」「KH Coderについて」を選択してバージョンをご確認ください。"
      placeholder: "記入例：3.00a, 3.Beta.06など。"
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "エラー・不具合について詳しくお書きください"
      description: "すでに入力されているテンプレートを編集しながらご記入ください"
      value: |
        ■お使いのOS
        →記入例：Windows 11, Windows 10, macOS 14, Ubuntu 18.04など
        
        ■KH Coderのインストール先フォルダ（解凍先フォルダ）
        →KH Coder起動時のコンソール画面に「CWD: C:\\khcoder3」のように表示されます。
        →記入例：C:\khcoder3
        
        ■どんなエラー・不具合・問題ですか？
        →「うまくいかない」のようなあいまいな書き方ではなく、「○○の結果を期待していたが、□□の結果になった」のように、できるだけ具体的にお書きください。
        →記入例：共起ネットワーク作成時に○△□を使おうとするとエラーになる。
        
        ■どのように操作すればその問題を再現できますか？
        →記入例：
        1. メニューから「ツール」「抽出語」「共起ネットワーク」を順にクリック
        2. 開いた「抽出語・共起ネットワーク：オプション」画面で「○△□」にチェックを入れてから「OK」をクリック
        
        ■エラー・メッセージ
        →省略や意訳をしていない一字一句そのままのエラーメッセージをお書きください。あるいはエラー画面・問題が起こった画面のスクリーンショットを添付してください。
        
        ■その問題はチュートリアルの漱石「こころ」データでも同様に発生しましたか？
        →データに原因があるのか、KH Coderの問題なのかを区別するために、チュートリアル・データでも同じ操作をお試しください。
        →記入例：はい、いいえ、他
        
        ■その問題を再現できるファイル（群）
        →その問題を再現できる分析対象ファイル等をなるべく添付してください。必要に応じてZip圧縮して添付してください。チュートリアルとして同梱されているファイルのみで問題を再現可能な場合は不要です。
        
        ■分析しようとしているのは何語のテキストですか？
        →記入例：日本語、英語、ロシア語、中国語など
        
        ■分析対象として指定しているファイルの形式は何ですか？
        →記入例：テキスト形式（.txt）、Excel形式（.xlsx）、CSV形式（.csv）など
        
        ■お使いのセキュリティ対策／ウイルス対策ソフトウェア
        →記入例：Norton 360, ウイルスバスター Corp Clientなど
        
        ■お使いのCPU
        →不明の場合はPCの機種名をお書きいただいてもOKです。
        →記入例：Intel Core i5, AMD Ryzen 5, Apple M1, Microsoft SQ2など
    validations:
      required: true


  - type: textarea
    id: console
    attributes:
      label: "コンソール・ウィンドウの表示内容（Macではターミナルの表示内容）"
      render: t
      description: |
        問題が生じたときのコンソール・ウィンドウの表示内容をすべてここにコピー＆ペーストしてください。長い場合は、内容をテキストファイル・Wordファイル等に保存し、そのファイルを貼り付けていただくのでも結構です。あるいはコンソール・ウィンドウのスクリーンショットを添付していただくのでもOKですが、できれば全内容のコピペの方が、手がかりを得られる可能性が高いです。
        
        Windows 10以前では、タスク・バーのKH Coderアイコンをクリックすれば、コンソール（Console）ウィンドウのアイコンが出てきます。Windows 11ではタスクバーのKH Coderアイコンの近くにコンソール（Console）ウィンドウのアイコンがあるケースが多いです。コンソール・ウィンドウとは黒の背景で，白い文字がずらずらと並んでいるウィンドウです。Windowsでのスクリーンショットの撮り方については、こちらをご覧下さい。
        https://support.hp.com/jp-ja/document/c03715297
        
        なおWindowsでは、KH Coderが起動しない場合はコンソール・ウィンドウも消えてしまって、表示内容を確認できません。この場合には、こちらのページに記載の手順でコンソール・ウィンドウの内容を確認してください。 http://khcoder.net/FAQ.html#vista
        
        Macの場合，エラー発生時のターミナルの表示内容をすべて，コピー＆ペーストでお知らせください。
    validations:
      required: true
