
labels: ["error"]
body:
  - type: markdown
    attributes:
      value: |
        # Before posting questions.
        
        This Discussions board is a place for users to help each other. The more clearly and in detail you can describe what you are having trouble with, the more likely you are to receive a helpful response. Especially, reporting the contents of console (terminal) window is essential for trouble shooting.
        
        When the problem is solved, please mark the helpful comment as \"answer\". Also, it is good manners to make comments such as \"This operation solved it\" or \"This document helped me understand\".
        
        # References
        
        Your issue may be resolved by referring to the following materials.
        
        * [Tutorial slides](https://khcoder.net/en/tutorial_slides.pdf) and [video](https://www.youtube.com/watch?v=ULhddsc2Nqo)
        * Detailed tutorial: [Part I](http://www.ritsumei.ac.jp/file.jsp?id=325881) & [Part II](http://www.ritsumei.ac.jp/file.jsp?id=346128)
        * [manual](https://khcoder.net/en/manual_en_v3.pdf)
        
        # Describe your issue in detail below

  - type: input
    id: version
    attributes:
      label: "Version number of KH Coder"
      description: "To check the version number, go to \"Help\" \"About\" in the menu of KH Coder. Please be sure to enter it correctly, such as \"3.Beta.07f\", not just \"3\"."
      placeholder: "e.g. 3.Beta.06, 2.00f, etc."
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: "Details about the error or the problem"
      value: |
        **OS**
        e.g. Windows 10, Ubuntu 20.04
        
        **The error message as detailed as possible**
        Please do not abbreviate or translate the message. Please tell me as it is, verbatim. If you don't like to type, you can attach a screenshot.
        
        **To Reproduce**
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        
        **Expected behavior**
        A clear and concise description of what you expected to happen.
        
        **What happens if you perform the same operation with the tutorial file (Anne.xls)**
        Can you get the intended result with tutorial data files? Or you get the same error? Please use "Anne.xls" in "tutorial_en" folder to test it out.
        
        **Files to Reproduce the Error**
        If we can't reproduce the error with the tutorial file "Anne.xls", please consider attaching files that can reproduce the Error.
        
        **Language of the Text**
        What language of text are you trying to analyze?
        e.g. English, Spanish
        
        **Type of the data file**
        What kind of file are you trying to analyze?
        e.g. Plain text (.txt), Excel (.xlsx), Word (.docx)
        
        **Screenshots**
        If applicable, add screenshots to help explain your problem.
        
        **CPU**
        e.g. Core i7, Atom
        
        **Antivirus or Security software running on the PC**
        e.g. Norton 360, Avast
        
        **Additional context**
        Add any other context about the problem.
    validations:
      required: true

  - type: textarea
    id: console
    attributes:
      label: "Contents of the console window"
      render: t
      description: |
        Other than errors in pop-up windows, the full console/terminal output really helps. On Windows, you can find the console window by clicking KH Coder icon in the [task bar](https://en.wikipedia.org/wiki/Taskbar#Microsoft_Windows). The window has white texts on a black background.
        
        If it is long, you can save the contents in a text file, Word file, etc. and paste the file. Alternatively, you can attach a screenshot of the console window, but if possible, a copy and paste of the entire content is more likely to give us a clue.
      value: |
        <details>
        <summary>Console messages...</summary>
        
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        
        ↓ Please paste it HERE ↓
        
        
        
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        </details>
    validations:
      required: true
